services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=mysql://root:rootpassword@db:3306/streamium
      - JWT_SECRET=development-jwt-secret
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TMDB_API_URL=https://api.themoviedb.org/3
      - TMDB_IMAGE_URL=https://image.tmdb.org/t/p
      - VIDSRC_BASE_URL=https://vidsrc.cc/v2/embed
      - VIDSRC_PRO_BASE_URL=https://vidsrc.pro/embed
      - EMBEDSU_BASE_URL=https://embed.su/embed
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=streamium
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
